import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const [text, setText] = useState<string>("");
  const { data, refetch } = api.shorten.insert.useQuery(
    { url: text },
    { enabled: false }
  );

  const handleSubmit = () => {
    refetch()
      .then((x) => x)
      .catch(() => void 0);
  };

  return (
    <div className="home">
      <Head>
        <title>Salatwürzer</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <img
          src="/salatwürzer.webp"
          alt="Salatwürzer"
          height="200px"
          width="200px"
        />
        <h1>Salatwürzer Linkverkürzer</h1>
        <input
          type="text"
          value={text}
          onChange={(e) => setText(e.target.value)}
          placeholder="Dein Link"
        />
        <button onClick={() => handleSubmit()}>Shorten URL</button>
        <h2 className="output">{data?.url ? <h2>{data.url}</h2> : null}</h2>
      </main>
    </div>
  );
};

export default Home;
